//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        public Nullable<decimal> Residential { get; set; }
        public Nullable<decimal> commerical { get; set; }
        public Nullable<decimal> one { get; set; }
        public Nullable<decimal> two { get; set; }
        public Nullable<decimal> three { get; set; }
        public Nullable<decimal> four { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> C { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> withinf { get; set; }
        public Nullable<decimal> withoutf { get; set; }
        public Nullable<decimal> proximity { get; set; }
        public Nullable<decimal> far { get; set; }
        public Nullable<decimal> paved { get; set; }
        public Nullable<decimal> unpaved { get; set; }
        public Nullable<decimal> existenceservices { get; set; }
        public Nullable<decimal> lackservices { get; set; }
        public Nullable<decimal> romured { get; set; }
        public Nullable<decimal> sorted { get; set; }
        public Nullable<decimal> financial { get; set; }
        public Nullable<decimal> newrent { get; set; }
        public Nullable<decimal> oldrent { get; set; }
        public Nullable<decimal> stoneland { get; set; }
        public Nullable<decimal> agriculturalland { get; set; }
        public Nullable<decimal> sandland { get; set; }
        public Nullable<decimal> littleslope { get; set; }
        public Nullable<decimal> midslope { get; set; }
        public Nullable<decimal> largeslope { get; set; }
        public Nullable<decimal> elevatorexist { get; set; }
        public Nullable<decimal> elavatornotexist { get; set; }
        public Nullable<decimal> buildingpermitexist { get; set; }
        public Nullable<decimal> buildingpermitnotexist { get; set; }
        public Nullable<decimal> upperfloar { get; set; }
        public Nullable<decimal> midfloar { get; set; }
        public Nullable<decimal> landfloar { get; set; }
        public Nullable<decimal> underlandfloar { get; set; }
        public Nullable<decimal> stoneandinsulatingmaterials { get; set; }
        public Nullable<decimal> naturalstone { get; set; }
        public Nullable<decimal> industrialstone { get; set; }
        public Nullable<decimal> blocks { get; set; }
        public Nullable<decimal> qualitygood { get; set; }
        public Nullable<decimal> qualitybad { get; set; }
        public Nullable<decimal> healthgood { get; set; }
        public Nullable<decimal> healthbad { get; set; }
        public Nullable<decimal> rebounds { get; set; }
        public Nullable<decimal> parkingexist { get; set; }
        public Nullable<decimal> parkingnotexist { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> reboundsexist { get; set; }
    }
}
